name = "texmo-hostel-hub"
main = "worker.js"
compatibility_date = "2026-09-30"

[[d1_databases]]
binding = "DB"
database_name = "texmo-hostel-db"
database_id = "9fa2fbaa-3538-46c5-9b88-fb399283cb5c"

[assets]
directory = "."
