name = "texmo-hostel-hub"
main = "worker.js"
compatibility_date = "2026-09-30"

[[d1_databases]]
binding = "DB"
database_name = "texmo-hostel-hub-v2"
database_id = "94fa1cc7-2633-4cea-8a8d-3e8e2e0f9856"

[assets]
directory = "."
